name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 20
          - 22
          - 24

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm ci
      - run: npm run test

  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    if: ${{ !cancelled() }}
    steps:
      - name: All matrix versions passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some matrix version failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1